name: rocketbot
description: Rocketbot

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.0
  flutter_secure_storage: ^5.0.2
  http: ^0.13.4
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  fl_chart: ^0.40.5
  cached_network_image: ^3.2.0
  animations: ^2.0.2
  progress_indicators: ^1.0.0


  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  generate: true

  assets:
    - images/


  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

