name: rocketbot
description: Rocketbot

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.40+40

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.0
  flutter_secure_storage: ^5.0.2
  firebase_messaging: any
  firebase_core: any
  http: ^0.13.4
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  fl_chart: ^0.40.6
  cached_network_image: ^3.2.0
  animations: ^2.0.2
  progress_indicators: ^1.0.0
  url_launcher: ^6.0.17
  webview_flutter_plus: ^0.2.3+1
  qr_flutter: ^4.0.0
  share: any
  vibration: ^1.7.4-nullsafety.0
  flutter_switch: ^0.3.2
  qr_code_scanner: ^0.6.1
  permission_handler: ^8.3.0
  local_auth: ^1.1.9
  flutter_phoenix: ^1.0.0
  package_info: any
  flutter_lock_screen: ^2.0.1

  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_launcher_name: ^0.0.1
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "RocketBot"

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  generate: true

  assets:
    - images/
    - webpages/


  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 300

