name: rocketbot
description: Rocketbot

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  http: ^0.13.4
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  fl_chart: ^0.40.2
  cached_network_image: ^3.2.0
  animations: ^2.0.2


  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/


  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

